sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
before_install:
  - npm i -g npm@3
before_script:
  - npm prune
after_success:
  - npm run semantic-release
env:
  matrix:
  - CLIENT=saucelabs:firefox:34 # pinning version, see https://code.google.com/p/selenium/issues/detail?id=8390
  - CLIENT=saucelabs:chrome
  - CLIENT=saucelabs:safari:6
  - CLIENT="saucelabs:iphone:8.1:OS X 10.9"
  - CLIENT="saucelabs:internet explorer:11:Windows 8.1"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
