sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
addons:
  apt:
    packages:
      - xvfb
      - gnome-keyring
      - libgnome-keyring-dev
node_js:
- iojs-v2
- iojs-v1
- '0.12'
- '0.10'
before_install: |
  case ${TRAVIS_NODE_VERSION} in
    iojs*)
      echo "Not upgrading npm for iojs."
      ;;
    *)
      npm update -g npm
      ;;
  esac
before_script:
- npm prune
- 'curl -Lo travis_after_all.py https://git.io/vLSON'
after_success:
- python travis_after_all.py
- export $(cat .to_export_back)
- if [[ $BUILD_LEADER = YES ]]; then npm run coverage:upload; fi
- npm run semantic-release
